name: Download

on:
  push:
    tags: v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v1
        
      - name: Download
        run: yt-dlp -f best '${{ secrets.URL }}'

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            *.mp4
