name: Download

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Setup yt-dlp
        uses: AnimMouse/setup-yt-dlp@v1
        
      - name: Download
        run: yt-dlp -o 'video.mp4' -f best '${{ secrets.URL }}'

      - uses: actions/upload-artifact@v3
        with:
          name: VIDEO
          path: video.mp4
