name: Download

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          
      - name: Setup youtube-dl
        uses: AnimMouse/setup-youtube-dl@v1
        
      - name: Download
        run: youtube-dl -o 'video.mp4' -f best 'https://www.youtube.com/watch?v=t5rYXC-4R-Q'

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          files: |
            video.mp4
